@echo off
:: =============================================================================
:: scripts\sign-apk.bat — Generate keystore and configure APK signing (Windows)
:: =============================================================================
:: Usage:
::   scripts\sign-apk.bat
::
:: What this script does:
::   1. Generates scripts\keys.jks
::   2. Creates android\app\key.properties
::
:: Prerequisites:
::   - Java JDK 17+ in PATH  (run scripts\install.bat first)
::
:: NOTE: Passwords are visible on screen in .bat files.
::       For secure (hidden) password input, use scripts\sign-apk.ps1 instead.
:: =============================================================================
setlocal EnableDelayedExpansion

set "SCRIPT_DIR=%~dp0"
set "PROJECT_ROOT=%SCRIPT_DIR%..\"
for %%i in ("%PROJECT_ROOT%") do set "PROJECT_ROOT=%%~fi"

set "KEYSTORE_PATH=%SCRIPT_DIR%keys.jks"
set "KEY_PROPS_PATH=%PROJECT_ROOT%android\app\key.properties"

echo.
echo ==========================================================
echo   TPQ Link ^— APK Signing Setup (Windows)
echo ==========================================================
echo.
echo NOTE: Use sign-apk.ps1 for hidden (secure) password input.
echo.

:: ── Check keytool ─────────────────────────────────────────────────────────────
keytool >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR]   keytool not found. Install Java JDK 17 and add JAVA_HOME\bin to PATH.
    echo           Run scripts\install.bat first.
    exit /b 1
)
echo [OK]      keytool found.

:: ── Handle existing keystore ──────────────────────────────────────────────────
set "SKIP_KEYGEN=0"
if exist "%KEYSTORE_PATH%" (
    echo [WARN]    keys.jks already exists at: %KEYSTORE_PATH%
    set /p "OVERWRITE=Overwrite existing keystore? [y/N]: "
    if /i "!OVERWRITE!"=="y" (
        set "SKIP_KEYGEN=0"
    ) else (
        set "SKIP_KEYGEN=1"
        echo [SIGN]    Keeping existing keystore.
    )
)

if !SKIP_KEYGEN!==0 (
    echo.
    echo Enter keystore information (press Enter to accept default):
    echo.

    set /p "KEY_ALIAS=  Key alias        [tpq-release]: "
    if "!KEY_ALIAS!"=="" set "KEY_ALIAS=tpq-release"

    set /p "KEY_PASSWORD=  Key password     (VISIBLE - use .ps1 for hidden): "
    if "!KEY_PASSWORD!"=="" (
        set "KEY_PASSWORD=tpq@Link2024"
        echo [WARN]    Using default password. Change it in production!
    )

    set /p "STORE_PASSWORD=  Store password   (Enter = same as key password): "
    if "!STORE_PASSWORD!"=="" set "STORE_PASSWORD=!KEY_PASSWORD!"

    set /p "CN=  Name / org       [TPQ Futuhil Hidayah]: "
    if "!CN!"=="" set "CN=TPQ Futuhil Hidayah"

    set /p "ORG=  Organization     [Futuhil Hidayah Wal Nikmah]: "
    if "!ORG!"=="" set "ORG=Futuhil Hidayah Wal Nikmah"

    set /p "CITY=  City             [Indonesia]: "
    if "!CITY!"=="" set "CITY=Indonesia"

    set /p "STATE=  State/Province   [Indonesia]: "
    if "!STATE!"=="" set "STATE=Indonesia"

    set /p "COUNTRY=  Country code     [ID]: "
    if "!COUNTRY!"=="" set "COUNTRY=ID"

    set /p "VALIDITY_YEARS=  Validity (years) [25]: "
    if "!VALIDITY_YEARS!"=="" set "VALIDITY_YEARS=25"
    set /a "VALIDITY_DAYS=!VALIDITY_YEARS! * 365"

    set "DNAME=CN=!CN!, OU=!ORG!, O=!ORG!, L=!CITY!, ST=!STATE!, C=!COUNTRY!"

    echo.
    echo [SIGN]    Generating keystore...
    echo [SIGN]      Path     : %KEYSTORE_PATH%
    echo [SIGN]      Alias    : !KEY_ALIAS!
    echo [SIGN]      Validity : !VALIDITY_YEARS! years
    echo.

    keytool -genkey -v ^
        -keystore "%KEYSTORE_PATH%" ^
        -storetype JKS ^
        -alias "!KEY_ALIAS!" ^
        -keyalg RSA -keysize 2048 ^
        -validity !VALIDITY_DAYS! ^
        -storepass "!STORE_PASSWORD!" ^
        -keypass "!KEY_PASSWORD!" ^
        -dname "!DNAME!"

    if %errorlevel% neq 0 (
        echo [ERROR]   keytool failed. Check your inputs and try again.
        exit /b 1
    )
    echo [OK]      keys.jks generated: %KEYSTORE_PATH%
) else (
    :: Use defaults if key.properties exists, otherwise use hardcoded defaults
    set "KEY_ALIAS=tpq-release"
    set "KEY_PASSWORD=tpq@Link2024"
    set "STORE_PASSWORD=tpq@Link2024"
    if exist "%KEY_PROPS_PATH%" (
        for /f "tokens=1,2 delims==" %%a in (%KEY_PROPS_PATH%) do (
            if "%%a"=="keyAlias"      set "KEY_ALIAS=%%b"
            if "%%a"=="keyPassword"   set "KEY_PASSWORD=%%b"
            if "%%a"=="storePassword" set "STORE_PASSWORD=%%b"
        )
    )
)

:: ── Write key.properties ──────────────────────────────────────────────────────
if not exist "%PROJECT_ROOT%android\app" mkdir "%PROJECT_ROOT%android\app"

echo [SIGN]    Writing key.properties to: %KEY_PROPS_PATH%

(
echo # ============================================================
echo # android/app/key.properties ^— Flutter release signing config
echo # Generated by scripts/sign-apk.bat
echo #
echo # WARNING: Do NOT commit this file to version control^^!
echo # ============================================================
echo.
echo storePassword=!STORE_PASSWORD!
echo keyPassword=!KEY_PASSWORD!
echo keyAlias=!KEY_ALIAS!
echo storeFile=%KEYSTORE_PATH%
) > "%KEY_PROPS_PATH%"

echo [OK]      key.properties written.

echo.
echo ==========================================================
echo   Signing setup complete^^!
echo ==========================================================
echo.
echo   Keystore   : %KEYSTORE_PATH%
echo   Properties : %KEY_PROPS_PATH%
echo.
echo   IMPORTANT: Keep keys.jks safe — losing it prevents Play Store updates^^!
echo.
echo   Next step: scripts\build-apk.bat --split-per-abi
echo.
endlocal
pause
